version: 2
updates:
  # Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"

  # Python dependencies (if requirements.txt exists)
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "python"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
