# Dynamic configuration
http:
  middlewares:
    # Basic Auth for Traefik Dashboard and Dockge
    auth:
      basicAuth:
        users:
          # ⚠️  SECURITY WARNING: CHANGE THIS IMMEDIATELY! ⚠️
          # Current credentials: admin:admin (DEFAULT - INSECURE!)
          # 
          # To generate a secure password hash:
          # 1. Install apache2-utils: sudo apt-get install apache2-utils
          # 2. Generate hash: echo $(htpasswd -nB admin) | sed -e s/\\$/\\$\\$/g
          # 3. Replace the line below with your generated hash
          # 
          # Example secure hash format:
          # - "admin:$2y$10$YOURGENERATEDHASHHERE"
          - "admin:$2y$10$2b2cu2Fw1ZfqRkqBfXkKyOeH69z9/oIpxVCD9gUseXJU6fcZWoKQC"
    
    # Security Headers
    security-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
    
    # Rate Limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 50

  # TLS Options
  tls:
    options:
      default:
        minVersion: "VersionTLS12"
        cipherSuites:
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          - "TLS_AES_256_GCM_SHA384"
          - "TLS_CHACHA20_POLY1305_SHA256"