name: Homelab Stack Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Validate Docker Compose
      run: |
        echo "🔍 Validating main docker-compose.yml..."
        docker compose -f docker-compose.yml config > /dev/null
        echo "✅ Docker Compose configuration is valid"

    - name: Check YAML syntax
      run: |
        echo "🔍 Checking YAML files..."
        # Basic YAML syntax check for compose files
        find . -name "*.yml" -o -name "*.yaml" | while read -r file; do
          echo "Checking: $file"
          python3 -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
        done
        echo "✅ All YAML files are valid"

    - name: Validate shell scripts
      run: |
        echo "🔍 Checking shell scripts..."
        find scripts/ -name "*.sh" | while read -r script; do
          echo "Checking: $script"
          bash -n "$script" || exit 1
        done
        echo "✅ All shell scripts have valid syntax"